name: "DEPLOY_BLOG"

on:
  workflow_dispatch:


jobs:
  generate-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: "Install Hexo CLI"
      run: npm install hexo-cli -g
    - run: cd backup/blog; npm install
    - run: cd backup/blog; hexo generate
    - name: Archive code Hexo results
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: backup/blog/public

  deploy-blog:
    needs: generate-blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Download code Hexo results"
        uses: actions/download-artifact@v3
        with:
          name: site
          path: backup/blog/public
      - name: "List Blog Files"
        run: ls -ila backup/blog/public
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: "Deploy GCP SDK"
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: "Deploy APPEngine"
        run: cd backup/blog/; gcloud -q --project=bloglinuxpro app deploy app.yaml -v=v$(date +'%Y%m%d-%H%M') --promote


